KLARNA_CHECKOUT_URL = ENV['SHF_KLARNA_CHECKOUT_URL']
KLARNA_ORDER_MGMT_URL = ENV['SHF_KLARNA_ORDER_MGMT_URL']

if Rails.env.production?
  KLARNA_MERCHANT_ID = ENV['SHF_KLARNA_MERCHANT_ID']
  KLARNA_SHARED_SECRET  = ENV['SHF_KLARNA_SHARED_SECRET']
else
  KLARNA_MERCHANT_ID = ENV['SHF_KLARNA_MERCHANT_ID_DEV']
  KLARNA_SHARED_SECRET  = ENV['SHF_KLARNA_SHARED_SECRET_DEV']
end

SHF_MEMBER_FEE   = 30000  # unit == one hundredth of krona
SHF_BRANDING_FEE = 25000

KLARNA_LOG = 'log/klarna.log'

SHF_WEBHOOK_HOST = ENV['SHF_DEV_WEBHOOK_HOST']
