KLARNA_ORDERS_URL = ENV['SHF_KLARNA_URL'] + 'orders/'

# if Rails.env.production?
#   HIPS_PRIVATE_KEY = ENV['SHF_HIPS_PRIVATE_KEY']
#   HIPS_PUBLIC_KEY  = ENV['SHF_HIPS_PUBLIC_KEY']
# else
#   HIPS_PRIVATE_KEY = ENV['SHF_HIPS_PRIVATE_KEY_DEV']
#   HIPS_PUBLIC_KEY  = ENV['SHF_HIPS_PUBLIC_KEY_DEV']
# end

SHF_MEMBER_FEE   = 30000  # unit == one hundredth of krona
SHF_BRANDING_FEE = 25000

KLARNA_LOG = 'log/klarna.log'

SHF_WEBHOOK_HOST = ENV['SHF_DEV_WEBHOOK_HOST']
